version: '3.6'
services:
  wiki-db:
    image: 'bitnami/mariadb:latest'
    container_name: wiki-db
    hostname: wiki-db
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_mwiki
      - MARIADB_DATABASE=mwiki
    volumes:
      - 'wiki_dbs:/bitnami'
  wiki:
    image: 'bitnami/mediawiki:latest'
    container_name: wiki
    hostname: wiki
    labels:
      kompose.service.type: nodeport
    environment:
      - MARIADB_HOST=wiki-db
      - MARIADB_PORT_NUMBER=3306
      - MEDIAWIKI_DATABASE_USER=bn_mwiki
      - MEDIAWIKI_DATABASE_NAME=bitnami_mwiki
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '8080:80'
    volumes:
      - 'wiki_data:/bitnami'
    depends_on:
      - wiki-db
  ninja-db:
    container_name: ninja-db
    image: mysql:5.6
    env_file: .env.ninja
    volumes:
      - ninja_dbs:/var/lib/mysql
    networks:
      - ninja-backend
    restart: always
  ninja-app:
    container_name: ninja-app
    image: invoiceninja/invoiceninja
    env_file: .env.ninja
    volumes:
      - ninja_stor:/var/www/app/storage:rw
      - ninja_logo:/var/www/app/public/logo:rw
    depends_on:
      - ninja-db
    networks:
      - ninja-backend
    restart: always
  ninja-web:
    container_name: ninja-web
    image: nginx
    volumes:
      - /mnt/nfs/dockerfiles/ninja/nginx.conf:/etc/nginx/nginx.conf:ro
      - ninja_stor:/var/www/app/storage:rw
      - ninja_logo:/var/www/app/public/logo:rw
    depends_on:
      - ninja-app
    ports:
      - 80:80
    networks:
      - ninja-backend
    restart: always
  cron:
    container_name: ninja-cron
    image: invoiceninja/invoiceninja
    depends_on:
      - ninja-db
    volumes:
      - ninja_stor:/var/www/app/storage:rw
      - ninja_logo:/var/www/app/public/logo:rw
    entrypoint: |
      bash -c 'bash -s <<EOF
      trap "break;exit" SIGHUP SIGINT SIGTERM
      sleep 300s
      while /bin/true; do
        ./artisan ninja:send-invoices
        ./artisan ninja:send-reminders
        sleep 1h
      done
      EOF'
    networks:
      - ninja-backend
    restart: always

volumes:
  wiki_dbs:
    driver_opts:
      type: none
      device: /mnt/nfs/dockerfiles/wiki/dbs
      o: bind
  wiki_data:
    driver_opts:
      type: none
      device: /mnt/nfs/dockerfiles/wiki/data
      o: bind
  ninja_stor:
      driver_opts:
        type: none
        device: /mnt/nfs/dockerfiles/ninja/storage
        o: bind
  ninja_logo:
    driver_opts:
      type: none
      device: /mnt/nfs/dockerfiles/ninja/logo
      o: bind
  ninja_dbs:
    driver_opts:
      type: none
      device: /mnt/nfs/dockerfiles/ninja/dbs
      o: bind
networks:
  ninja-backend:
  wiki-backend:
